### PR TITLE
Migrate content to tech doc website

### PR DESCRIPTION
**Pull request by Pilargit12**
Rocket.Chat (new section)
Steps to join Rocket.Chat.md
Rocket.Chat etiquette.md
Rocket.Chat channel descriptions.md
Get help in Rocket.Chat.md

### CODE REVIEW

**Comment by mtspn** [comment]
Hey Pilar, it looks like these changes were merged before either of us had a chance to review them? Do you still looking for a review after-the-fact?

**Comment by Pilargit12** [comment]
Yes I made the mistake Matt of pushing through. These are pages that are in the same format at the private cloud currently, and I just created a new section called Rocket.Chat and just 4 pages below the category.  I haven't created the build yet though.

**Comment by mtspn** [comment]
I'm not sure I understand this decision. In my opinion, these pages are a good fit in their current location on the private cloud site as they are applicable to product owners and less technical roles. Was this discussed at sprint planning (apologies if I didn't catch this then!) or was the ticket introduced mid-sprint?

**Comment by mtspn** [comment]
Just to follow up on the ticket, Pilar and I had a conversation about why these pages can fit in technical docs and the reasoning behind moving them. Pilar had created this ticket mid-sprint to account for some of the rocketchat pages being removed by the content design team from the private cloud website. With the extra context I think it does make sense to move these pages over to the tech docs site.

**Pull request merged**
