### PR TITLE
Update platform-architecture-diagram.md

### PR DESCRIPTION
**Pull request by conbrad**
Simplify access to internal resources by directly linking to https://digital.gov.bc.ca/cloud/services/private/internal-resources/diagram/

### CODE REVIEW

**Review by Pilargit12 — COMMENTED** [review]
May I know why the steps where removed to view the diagram in the internal resources page?

**Comment by conbrad** [comment]
> May I know why the steps where removed to view the diagram in the internal resources page?

Why add steps when you can direct link?

**Review by Pilargit12 — APPROVED** [review]

**Comment by Pilargit12** [comment]
Will update this through https://github.com/bcgov/platform-developer-docs/pull/250

**Comment by conbrad** [comment]
> @conbrad the link you shared still requires login though, perhaps you were already logged in when testing this?

The description of the link already states it's IDIR protected.

**Comment by mtspn** [comment]
I appreciate the suggestion, and agree to an extent that it should be obvious, but we've learned a lot of things that should be self explanatory often aren't for everybody. I think in this case it's reasonable to err on the the side of the explanation, since we aren't able to directly link to the diagram and there is no redirect after logging in.

**Comment by mtspn** [comment]
I've just tested again and it looks the digital.gov site will now redirect to the architecture diagram after login rather than return people to the higher-level page. So now that this process is simpler, I think the instructions can be too. Cheers Connor!

**Comment by mtspn** [comment]
This seems to behave differently depending on which browser I use. I've just tested with Firefox, and the direct link redirects back to digital.gov.bc.ca after login. This behaviour is why we had the instructions. 

https://github.com/bcgov/platform-developer-docs/assets/99685508/d33f8259-42fa-4691-9b18-95a4f004842e

**Comment by conbrad** [comment]
> This seems to behave differently depending on which browser I use. I've just tested with Firefox, and the direct link redirects back to digital.gov.bc.ca after login. This behaviour is why we had the instructions.
> 
>  architechture.link.mov

Ah I see, thanks for clarifying @mtspn , I'm ignorant toward non-chromium browsers. I was thinking we could rely on the web in it's purest form and save on some words but reality strikes 😅

**Pull request closed without merging**
